blank_issues_enabled: false
contact_links:
  - name: CodeAgent.new related issues
    url: https://github.com/stackblitz/codeagent.new/issues/new/choose
    about: Report issues related to CodeAgent.new (not CodeAgent.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other CodeAgent.diy users.
